### PR TITLE
generate for 1.13

### PR DESCRIPTION
**Pull request by tg123**

### CODE REVIEW

**Comment by brendandburns** [comment]
Thanks! Can you squash this down into two commits:

1) new API changes
2) fixes to examples, etc.

Thanks!

**Comment by tg123** [comment]
done
another commit is for updating the cert used in test

**Comment by brendandburns** [comment]
Let's rev the version to 1.4 with this also.

**Comment by tg123** [comment]
@brendandburns already bumped up to 1.4
```
  -"version": "1.3",
  +"version": "1.4",
```

**Comment by brendandburns** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
