### PR TITLE
RFC - Support WebSockets with channels

### PR DESCRIPTION
**Pull request by qmfrederik**
The port forward, attach and exec commands all return WebSockets which contain data in different channels.

This PR adds code which can take such as `WebSocket` and decompose (de-multiplex) it into different `Streams`.

A client could use this API like this:

```
using (WebSocket webSocket = await kubernetes.WebSocketNamespacedPodPortforwardAsync(webDriverPod.Metadata.Name, "8080", 17894, null, default(CancellationToken)).ConfigureAwait(false))
using (StreamDemuxer muxer = new StreamDemuxer(webSocket))
using (Stream stream = muxer.GetStream(0, 0))
{
    // You can read/write to the stream here to interact with the remote socket.
}
```

From a design point of view, the `StreamDemuxer` class has a `ClientLoop` which reads all the data of the `WebSocket` and stores it in individual `ByteBuffers` - one for each channel.

For each channel, there's a corresponding `DemuxedStream` which reads the bytes from the `ByteBuffer` class. So you get a producer-consumer implementation.

As outlined in the other issue, I'm not entirely satisfied with this implementation because of the buffering, but it may be a good first start.

Opening the PR mainly to get your feedback, let me know what you think!

### CODE REVIEW

**Comment by brendandburns** [comment]
This looks like a good approach to me. In the Java implementation I used PipedInput/OutputStreams for a similar sort of feel.

**Comment by brendandburns** [comment]
(oh and sorry for the delay in responding...)

**Comment by brendandburns** [comment]
Though there are build errors:

```
Copyright (C) Microsoft Corporation. All rights reserved.

StreamDemuxer.cs(38,16): error CS0246: The type or namespace name 'Stream' could not be found (are you missing a using directive or an assembly reference?) [/home/travis/build/kubernetes-client/csharp/src/KubernetesClient.csproj]

Build FAILED.

StreamDemuxer.cs(38,16): error CS0246: The type or namespace name 'Stream' could not be found (are you missing a using directive or an assembly reference?) [/home/travis/build/kubernetes-client/csharp/src/KubernetesClient.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:07.65
StreamDemuxer.cs(38,16): error CS0246: The type or namespace name 'Stream' could not be found (are you missing a using directive or an assembly reference?) [/home/travis/build/kubernetes-client/csharp/src/KubernetesClient.csproj]

Build FAILED.

StreamDemuxer.cs(38,16): error CS0246: The type or namespace name 'Stream' could not be found (are you missing a using directive or an assembly reference?) [/home/travis/build/kubernetes-client/csharp/src/KubernetesClient.csproj]

    0 Warning(s)
    1 Error(s)
```

**Comment by qmfrederik** [comment]
@brendandburns Thanks! The build issue should be fixed now.

**Comment by brendandburns** [comment]
LGTM, merging.

**Pull request merged**
