### PR TITLE
Gen v1.19.3

### PR DESCRIPTION
**Pull request by tg123**
generated with latest generator including 401 related changes

### CODE REVIEW

**Comment by brendandburns** [comment]
Thanks! Tests are failing, looks like perhaps the auto-rest code changed somewhat?

**Comment by tg123** [comment]
yes 401 throws now, breaks current tests.

I am fixing

**Comment by tg123** [comment]
link #493

**Comment by brendandburns** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
