### PR TITLE
change lib target to netstandard13

### PR DESCRIPTION
**Pull request by tg123**
1. make lib work in netstandard 1.3 #32 
1. add root namespace

### CODE REVIEW

**Comment by tg123** [comment]
seems need to test on mac.

**Comment by krabhishek8260** [comment]
We have to stick to dotnet core 2.0 for now because the cert apis to set private key is only avaibale in dotnetcore 2.0.

**Comment by tg123** [comment]
hi @krabhishek8260 
I have found the dotnet standard way to generate the cert see 8e9ed00fc3d4917cbf841e3119101035fe87469a and #27

**Comment by krabhishek8260** [comment]
LGTM. This is great. Thanks!

**Pull request merged**
