### PR TITLE
Fix - Not applied patch if path contains Uppercase

### LINKED ISSUE #329: Not applied patch if path contains Uppercase
### Repro code, Cause and Workaround
```csharp
using System;
using k8s;
using k8s.Models;
using Microsoft.AspNetCore.JsonPatch;

namespace patch
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            var config = KubernetesClientConfiguration.BuildConfigFromConfigFile();
            IKubernetes client = new Kubernetes(config);
            Console.WriteLine("Starting Request!");

            var patch = new JsonPatchDocument<V1HorizontalPodAutoscaler>();
            patch.Replace(h => h.Spec.MinReplicas, 10);

            // Root cause, Path does not honor JsonProperty. so, it would be /spec/minreplicas
            Console.WriteLine(patch.Operations[0].path);
            // Workaround
            patch.Operations[0].path = "/spec/minReplicas";

            var name = "<target-hpa>";
            var result = client.PatchNamespacedHorizontalPodAutoscaler(new V1Patch(patch), name, "default");

            Console.WriteLine(result.Spec.MinReplicas);
        }
    }
}
```
 - Latest `Microsoft.AspNetCore.JsonPatch` had been resolved this issue.
 - Will PR later.

### PR DESCRIPTION
**Pull request by idubnori**
Fix #329

### Progress
- [x] Add repro code
- [x] Upgrade `Microsoft.AspNetCore.JsonPatch` to the latest version

### CODE REVIEW

**Comment by idubnori** [comment]
Signed the CLA

**Comment by brendandburns** [comment]
/lgtm
/approve

Thanks!

**Comment by idubnori** [comment]
@brendandburns I am happy to contribute and got your review.
Thanks, too!

**Pull request merged**
