### PR TITLE
Kubernetes.Classic: add support for netstandard2.0 and net48

### LINKED ISSUE #743: Framework no longer supported
In PR https://github.com/kubernetes-client/csharp/pull/603 the code was switched from emitting .netstandard 2.0 to .netstandard 2.1 . Can we change this back to .netstandard 2.0 Otherwise cannot use this package with .net Framework. 
@tg123

### PR DESCRIPTION
**Pull request by tg123**
fix #743

support basic API call for older .net runtime, watcher, exec etc. are not supported at the moment

### CODE REVIEW

**Comment by tg123** [comment]
/hold

trying to run some basic ut

**Comment by brendandburns** [comment]
\lgtm
\approve

**Comment by tg123** [comment]
I am going to merge it as windows style `\` is not recognized by bot

**Pull request merged**
