### PR TITLE
Stylecop

### PR DESCRIPTION
**Pull request by tg123**
add style analyzer to repo

- https://github.com/dotnet/roslyn-analyzers
- https://github.com/DotNetAnalyzers/StyleCopAnalyzers 

and first enforced rule

- no tab allowed <https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1027.md>

also put `<autogenerated>` headers to generate files in order to be ignored by analyzers

### CODE REVIEW

**Comment by tg123** [comment]
6313 Warning(s) by far
will continue improving code quality

**Comment by brendandburns** [comment]
This looks fine to me. I simultaneously added `dotnet format` (#431)

**Comment by brendandburns** [comment]
We should add validation to the github action.

**Comment by tg123** [comment]
for sure
the ruleset where there is a xx=error would block building from success 

i only added sa1027 to error list
and more rule restrictions will be enabled after cleaning up warnings

**Pull request merged**
