### PR TITLE
Bump down Newtonsoft.Json package to 9.0.1 from 10.0.2. Add reference…

### PR DESCRIPTION
**Pull request by pragyamehta**
… to System.ComponentModel.TypeConverter to fix build.

### CODE REVIEW

**Comment by brendandburns** [comment]
@pragyamehta Why is this needed?

Thanks

**Comment by pragyamehta** [comment]
I signed it

**Comment by brendandburns** [comment]
This is needed to temporarily resolve some issues with version conflicts between AutoRest and our use of NewtonSoft. AutoRest is tracking fixes so that we can re-fix the dependencies here.

/lgtm
/approve

**Comment by tg123** [comment]
sorry I am not quite clear about the fix.
any more info about the conflict?

**Pull request merged**
