### PR TITLE
feat: switch JsonConverters to public for Source Generators

### LINKED ISSUE #1309: Using System.Text.Json Source Generator
I'm playing with utilizing the Source Generator approach in the Json Serializer in order to optimize performance of informers.

Benefits of this approach:
image

See these two docs:
- https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator/
- https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation

Unfortunately, I've hit a snag due to the existing Json converters being internal.

image

Options:
1. Make existing converters public
2. Add Source Generation to this library
   1. It appears fairly simple to implement
   2. 
            KubernetesJson.AddJsonOptions(x => x.TypeInfoResolver = JsonTypeInfoResolver.Combine(SourceGenerationContext.Default, JsonSerializerOptions.Default.TypeInfoResolver));

            [JsonSerializable(typeof(V1Node))]
            [JsonSerializable(typeof(V1Namespace))]
            .. add all other types
            internal partial class SourceGenerationContext : JsonSerializerContext
            {
            }

 
 Thoughts?
```[tasklist]
### Tasks
- [ ] https://github.com/kubernetes-client/csharp/pull/1417
```

### PR DESCRIPTION
**Pull request by IvanJosipovic**
Fixes #1309

### CODE REVIEW

**Comment by tg123** [comment]
will the pr include Source Generators?

**Comment by IvanJosipovic** [comment]
> will the pr include Source Generators?

I can look to add the Source Generator, the code will need to be added to the Model generation code of this code base so that its dynamic.

There is also a fallback to the Reflection based Serializer if the Source Gen doesn't exist:

```
KubernetesJson.AddJsonOptions(x => x.TypeInfoResolver = JsonTypeInfoResolver.Combine(SourceGenerationContext.Default, JsonSerializerOptions.Default.TypeInfoResolver));
```

Here is what my Source Generator looks like at the moment
```
using System.Text.Json;
using System.Text.Json.Serialization;

namespace KubeUI.Core.Client.Serialization
{
    [JsonSerializable(typeof(V1Node))]
    [JsonSerializable(typeof(KubernetesList<V1Node>))]
    [JsonSerializable(typeof(Watcher<V1Node>.WatchEvent))]

    [JsonSerializable(typeof(V1Namespace))]
    [JsonSerializable(typeof(KubernetesList<V1Namespace>))]
    [JsonSerializable(typeof(Watcher<V1Namespace>.WatchEvent))]

    [JsonSerializable(typeof(Corev1Event))]
    [JsonSerializable(typeof(KubernetesList<Corev1Event>))]
    [JsonSerializable(typeof(Watcher<Corev1Event>.WatchEvent))]

    [JsonSerializable(typeof(V1Pod))]
    [JsonSerializable(typeof(KubernetesList<V1Pod>))]
    [JsonSerializable(typeof(Watcher<V1Pod>.WatchEvent))]

    [JsonSerializable(typeof(V1Deployment))]
    [JsonSerializable(typeof(KubernetesList<V1Deployment>))]
    [JsonSerializable(typeof(Watcher<V1Deployment>.WatchEvent))]

    [JsonSerializable(typeof(V1DaemonSet))]
    [JsonSerializable(typeof(KubernetesList<V1DaemonSet>))]
    [JsonSerializable(typeof(Watcher<V1DaemonSet>.WatchEvent))]

    [JsonSerializable(typeof(V1StatefulSet))]
    [JsonSerializable(typeof(KubernetesList<V1StatefulSet>))]
    [JsonSerializable(typeof(Watcher<V1StatefulSet>.WatchEvent))]

    [JsonSerializable(typeof(V1ReplicaSet))]
    [JsonSerializable(typeof(KubernetesList<V1ReplicaSet>))]
    [JsonSerializable(typeof(Watcher<V1ReplicaSet>.WatchEvent))]

    [JsonSerializable(typeof(V1ReplicationController))]
    [JsonSerializable(typeof(KubernetesList<V1ReplicationController>))]
    [JsonSerializable(typeof(Watcher<V1ReplicationController>.WatchEvent))]

    [JsonSerializable(typeof(V1Job))]
    [JsonSerializable(typeof(KubernetesList<V1Job>))]
    [JsonSerializable(typeof(Watcher<V1Job>.WatchEvent))]

    [JsonSerializable(typeof(V1CronJob))]
    [JsonSerializable(typeof(KubernetesList<V1CronJob>))]
    [JsonSerializable(typeof(Watcher<V1CronJob>.WatchEvent))]

    [JsonSerializable(typeof(V1ConfigMap))]
    [JsonSerializable(typeof(KubernetesList<V1ConfigMap>))]
    [JsonSerializable(typeof(Watcher<V1ConfigMap>.WatchEvent))]

    [JsonSerializable(typeof(V1Secret))]
    [JsonSerializable(typeof(KubernetesList<V1Secret>))]
    [JsonSerializable(typeof(Watcher<V1Secret>.WatchEvent))]

    [JsonSerializable(typeof(V1ResourceQuota))]
    [JsonSerializable(typeof(KubernetesList<V1ResourceQuota>))]
    [JsonSerializable(typeof(Watcher<V1ResourceQuota>.WatchEvent))]

    [JsonSerializable(typeof(V1LimitRange))]
    [JsonSerializable(typeof(KubernetesList<V1LimitRange>))]
    [JsonSerializable(typeof(Watcher<V1LimitRange>.WatchEvent))]

    [JsonSerializable(typeof(V1HorizontalPodAutoscaler))]
    [JsonSerializable(typeof(KubernetesList<V1HorizontalPodAutoscaler>))]
    [JsonSerializable(typeof(Watcher<V1HorizontalPodAutoscaler>.WatchEvent))]

    [JsonSerializable(typeof(V1PodDisruptionBudget))]
    [JsonSerializable(typeof(KubernetesList<V1PodDisruptionBudget>))]
    [JsonSerializable(typeof(Watcher<V1PodDisruptionBudget>.WatchEvent))]

    [JsonSerializable(typeof(V1PriorityClass))]
    [JsonSerializable(typeof(KubernetesList<V1PriorityClass>))]
    [JsonSerializable(typeof(Watcher<V1PriorityClass>.WatchEvent))]

    [JsonSerializable(typeof(V1RuntimeClass))]
    [JsonSerializable(typeof(KubernetesList<V1RuntimeClass>))]
    [JsonSerializable(typeof(Watcher<V1RuntimeClass>.WatchEvent))]

    [JsonSerializable(typeof(V1Lease))]
    [JsonSerializable(typeof(KubernetesList<V1Lease>))]
    [JsonSerializable(typeof(Watcher<V1Lease>.WatchEvent))]

    [JsonSerializable(typeof(V1APIService))]
    [JsonSerializable(typeof(KubernetesList<V1APIService>))]
    [JsonSerializable(typeof(Watcher<V1APIService>.WatchEvent))]

    [JsonSerializable(typeof(V1Service))]
    [JsonSerializable(typeof(KubernetesList<V1Service>))]
    [JsonSerializable(typeof(Watcher<V1Service>.WatchEvent))]

    [JsonSerializable(typeof(V1Endpoints))]
    [JsonSerializable(typeof(KubernetesList<V1Endpoints>))]
    [JsonSerializable(typeof(Watcher<V1Endpoints>.WatchEvent))]

    [JsonSerializable(typeof(V1EndpointSlice))]
    [JsonSerializable(typeof(KubernetesList<V1EndpointSlice>))]
    [JsonSerializable(typeof(Watcher<V1EndpointSlice>.WatchEvent))]

    [JsonSerializable(typeof(V1Ingress))]
    [JsonSerializable(typeof(KubernetesList<V1Ingress>))]
    [JsonSerializable(typeof(Watcher<V1Ingress>.WatchEvent))]

    [JsonSerializable(typeof(V1IngressClass))]
    [JsonSerializable(typeof(KubernetesList<V1IngressClass>))]
    [JsonSerializable(typeof(Watcher<V1IngressClass>.WatchEvent))]

    [JsonSerializable(typeof(V1NetworkPolicy))]
    [JsonSerializable(typeof(KubernetesList<V1NetworkPolicy>))]
    [JsonSerializable(typeof(Watcher<V1NetworkPolicy>.WatchEvent))]

    [JsonSerializable(typeof(V1MutatingWebhookConfiguration))]
    [JsonSerializable(typeof(KubernetesList<V1MutatingWebhookConfiguration>))]
    [JsonSerializable(typeof(Watcher<V1MutatingWebhookConfiguration>.WatchEvent))]

    [JsonSerializable(typeof(V1ValidatingWebhookConfiguration))]
    [JsonSerializable(typeof(KubernetesList<V1ValidatingWebhookConfiguration>))]
    [JsonSerializable(typeof(Watcher<V1ValidatingWebhookConfiguration>.WatchEvent))]

    [JsonSerializable(typeof(V1PersistentVolumeClaim))]
    [JsonSerializable(typeof(KubernetesList<V1PersistentVolumeClaim>))]
    [JsonSerializable(typeof(Watcher<V1PersistentVolumeClaim>.WatchEvent))]

    [JsonSerializable(typeof(V1PersistentVolume))]
    [JsonSerializable(typeof(KubernetesList<V1PersistentVolume>))]
    [JsonSerializable(typeof(Watcher<V1PersistentVolume>.WatchEvent))]

    [JsonSerializable(typeof(V1StorageClass))]
    [JsonSerializable(typeof(KubernetesList<V1StorageClass>))]
    [JsonSerializable(typeof(Watcher<V1StorageClass>.WatchEvent))]

    [JsonSerializable(typeof(V1ServiceAccount))]
    [JsonSerializable(typeof(KubernetesList<V1ServiceAccount>))]
    [JsonSerializable(typeof(Watcher<V1ServiceAccount>.WatchEvent))]

    [JsonSerializable(typeof(V1ClusterRole))]
    [JsonSerializable(typeof(KubernetesList<V1ClusterRole>))]
    [JsonSerializable(typeof(Watcher<V1ClusterRole>.WatchEvent))]

    [JsonSerializable(typeof(V1Role))]
    [JsonSerializable(typeof(KubernetesList<V1Role>))]
    [JsonSerializable(typeof(Watcher<V1Role>.WatchEvent))]

    [JsonSerializable(typeof(V1ClusterRoleBinding))]
    [JsonSerializable(typeof(KubernetesList<V1ClusterRoleBinding>))]
    [JsonSerializable(typeof(Watcher<V1ClusterRoleBinding>.WatchEvent))]

    [JsonSerializable(typeof(V1RoleBinding))]
    [JsonSerializable(typeof(KubernetesList<V1RoleBinding>))]
    [JsonSerializable(typeof(Watcher<V1RoleBinding>.WatchEvent))]

    [JsonSerializable(typeof(V1CustomResourceDefinition))]
    [JsonSerializable(typeof(KubernetesList<V1CustomResourceDefinition>))]
    [JsonSerializable(typeof(Watcher<V1CustomResourceDefinition>.WatchEvent))]

    [JsonSerializable(typeof(V1APIGroupList))]
    [JsonSerializable(typeof(KubernetesList<V1APIGroupList>))]
    [JsonSerializable(typeof(Watcher<V1APIGroupList>.WatchEvent))]

    [JsonSerializable(typeof(V1LimitRange))]
    [JsonSerializable(typeof(KubernetesList<V1LimitRange>))]
    [JsonSerializable(typeof(Watcher<V1LimitRange>.WatchEvent))]

    [JsonSerializable(typeof(V1WatchEvent))]
    [JsonSerializable(typeof(KubernetesObject))]
    [JsonSerializable(typeof(Watcher<KubernetesObject>.WatchEvent))]

    [JsonSerializable(typeof(JsonElement))]
    internal partial class SourceGenerationContext : JsonSerializerContext
    {
    }
}

```

**Comment by guillaume-chervet** [comment]
Any news on this PullRequest :p

**Comment by guillaume-chervet** [comment]
hi @IvanJosipovic ,

may you rebase your PullRequest for a merge ?
I really need this :p

**Comment by guillaume-chervet** [comment]
Does this PullRequest ready to review @brendandburns ?

**Comment by tg123** [comment]
> Does this PullRequest ready to review @brendandburns ?

i am working in another pr of aot

**Comment by guillaume-chervet** [comment]
Any news about this PR?
It is blocking trimming.

```
2023-12-06 17:56:19 Unhandled exception. System.AggregateException: One or more errors occurred. (Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.)
2023-12-06 17:56:19  ---> System.InvalidOperationException: Reflection-based serialization has been disabled for this application. Either use the source generator APIs or explicitly configure the 'JsonSerializerOptions.TypeInfoResolver' property.
2023-12-06 17:56:19    at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerIsReflectionDisabled()
2023-12-06 17:56:19    at System.Text.Json.JsonSerializerOptions.ConfigureForJsonSerializer()
2023-12-06 17:56:19    at System.Text.Json.JsonSerializerOptions.MakeReadOnly(Boolean)
2023-12-06 17:56:19    at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions, Type)
2023-12-06 17:56:19    at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions)
2023-12-06 17:56:19    at System.Text.Json.JsonSerializer.Deserialize[TValue](Stream , JsonSerializerOptions )
2023-12-06 17:56:19    at k8s.KubernetesJson.Deserialize[TValue](Stream json, JsonSerializerOptions jsonSerializerOptions)
2023-12-06 17:56:19    at k8s.Kubernetes.CreateResultAsync[T](HttpRequestMessage httpRequest, HttpResponseMessage httpResponse, Nullable`1 watch, CancellationToken cancellationToken)
2023-12-06 17:56:19    at k8s.AbstractKubernetes.ICoreV1Operations_ListNamespacedPodWithHttpMessagesAsync[T](String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 sendInitialEvents, Nullable`1 timeoutSeconds, Nullable`1 watch, Nullable`1 pretty, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)
2023-12-06 17:56:19    at k8s.AbstractKubernetes.k8s.ICoreV1Operations.ListNamespacedPodWithHttpMessagesAsync(String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 sendInitialEvents, Nullable`1 timeoutSeconds, Nullable`1 watch, Nullable`1 pretty, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)
2023-12-06 17:56:19    at k8s.CoreV1OperationsExtensions.ListNamespacedPodAsync(ICoreV1Operations operations, String namespaceParameter, Nullable`1 allowWatchBookmarks, String continueParameter, String fieldSelector, String labelSelector, Nullable`1 limit, String resourceVersion, String resourceVersionMatch, Nullable`1 sendInitialEvents, Nullable`1 timeoutSeconds, Nullable`1 watch, Nullable`1 pretty, CancellationToken cancellationToken)
2023-12-06 17:56:19    at SlimFaas.Kubernetes.KubernetesService.ListFunctionsAsync(String kubeNamespace)
2023-12-06 17:56:19    at SlimFaas.ReplicasService.SyncDeploymentsAsync(String kubeNamespace)
2023-12-06 17:56:19    --- End of inner exception stack trace ---
2023-12-06 17:56:19    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean)
2023-12-06 17:56:19    at System.Threading.Tasks.Task.Wait(Int32, CancellationToken)
2023-12-06 17:56:19    at System.Threading.Tasks.Task.Wait()
2023-12-06 17:56:19    at Program.<Main>$(String[] args)
2023-12-06 17:56:19 Starting in namespace slimfaas-demo
```

**Comment by tg123** [comment]
close as of #1498

**Pull request closed without merging**
