### PR TITLE
Standardization of using order and object initialization

### PR DESCRIPTION
**Pull request by m3nax**
Another pull request that tries to improve the readability of the code.

### CODE REVIEW

**Comment by tg123** [comment]
thanks
jealous of `go fmt`

btw what tool are you using? resharper?

/LGTM

**Comment by m3nax** [comment]
> thanks jealous of `go fmt`
> 
> btw what tool are you using? resharper?
> 
> /LGTM

I'm using code cleanup and a little patience to fix the errors it generates
image

**Comment by brendandburns** [comment]
/approve

I will let @tg123 give the final lgtm.

**Review by tg123 — APPROVED** [review]
/LGTM

**Pull request merged**
