### PR TITLE
Move to net8.0

### PR DESCRIPTION
**Pull request by m3nax**
.Net 8.0 was released, in order to start the migration to the newer version of framework i updated the .net version of examples to the latest. I also accorgitly updated actions to build the update projects.

### CODE REVIEW

**Comment by tg123** [comment]
great, why not move main lib to net8 as well?

**Comment by m3nax** [comment]
> great, why not move main lib to net8 as well?

I will do it in the next few days

**Comment by m3nax** [comment]
@tg123 Work done

**Comment by tg123** [comment]
could you please also bump ver to 12.2
https://github.com/kubernetes-client/csharp/blob/c74400f987a2c63c2bc63a90484d0d6220c28aec/version.json#L3C15-L3C19

**Comment by m3nax** [comment]
@tg123 Done

**Review by tg123 — APPROVED** [review]
/LGTM

**Comment by tg123** [comment]
seems testcases need some upgrade

```
Expected: typeof(System.IO.IOException)
Actual:   typeof(System.Net.Http.HttpIOException)
```

**Comment by m3nax** [comment]
> seems testcases need some upgrade
> 
> ```
> Expected: typeof(System.IO.IOException)
> Actual:   typeof(System.Net.Http.HttpIOException)
> ```

Yes but it is strange that with net 6/7 the exception is System.IO.IOException with 8 is System.Net.Http.HttpIOException, it is a breaking change

**Comment by tg123** [comment]
catch HttpIOException | IOExcpetion?

**Comment by m3nax** [comment]
```
[xUnit.net 00:05:04.32]     Can exec in pod's default container, STDOUT only [FAIL]
  Failed Can exec in pod's default container, STDOUT only [11 s]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync(MessageOpcode opcode, Boolean endOfMessage, Boolean disableCompression, ReadOnlyMemory`1 payloadBuffer, Task lockTask, CancellationToken cancellationToken)
   at k8s.Tests.WebSocketTestBase.SendMultiplexed(WebSocket webSocket, Byte streamIndex, String text) in /_/tests/KubernetesClient.Tests/WebSocketTestBase.cs:line 266
   at k8s.Tests.PodExecTests.ExecDefaultContainerStdOut() in /_/tests/KubernetesClient.Tests/PodExecTests.cs:line 85
--- End of stack trace from previous location ---
  Standard Output Messages:
 Invoking exec operation...
 Test-level cancellation token has been canceled.
 Client socket connected (socket state is Open). Waiting for server-side socket to become available...
 Server-side socket is now available (socket state is Open). Sending data to server socket...


Results File: D:\a\csharp\csharp\TestResults\runneradmin_fv-az742-628_2023-11-27_10_09_15.trx

Failed!  - Failed:     1, Passed:   189, Skipped:     2, Total:   192, Duration: 4 m 56 s - KubernetesClient.Tests.dll (net6.0)
```

Looks like we've hit the job timeout... Right?

**Comment by m3nax** [comment]
@tg123 Why are the compilation and testing actions not started?

**Review by tg123 — APPROVED** [review]

**Pull request merged**
