### PR TITLE
remove unused util code

### PR DESCRIPTION
**Pull request by tg123**
- remove duplicated generic code which impled 
- remove unfinished cache/informer code (still missing informer reflector ...)

### CODE REVIEW

**Comment by tg123** [comment]
#846

**Comment by koepalex** [comment]
We used in our code the `GenericKubernetesApi` to watch kubernetes resources (namespaces scoped and global), this class was removed from nuget `9.0.x`

```csharp
// constructor
_genericClient = new GenericClient(_kubernetesClient, GROUP, VERSION, PLURAL);
_genericKubernetesApi = new GenericKubernetesApi(GROUP, VERSION, PLURAL, _kubernetesClient);
// later
var watcher = _genericKubernetesApi.Watch(NAMESPACE, onEvent, onError, onClosed, cancellationToken);
```

We are using this approach to be able to reconnect when the connection is lost (onClosed) and for the error logging.
With removing of the API, I think we need to change to, the way shown in [Watch Example](https://github.com/kubernetes-client/csharp/blob/master/examples/watch/Program.cs). 

But how can we deal with _reconnect_ and _error logging_ in that case?

**Comment by tg123** [comment]
thanks for reporting, will add `watch` as requested

**Comment by brendandburns** [comment]
@tg123 will watch be added to this PR? Or in a follow up?

**Comment by tg123** [comment]
> @tg123 will watch be added to this PR? Or in a follow up?

lets do it in followup

**Pull request merged**
