### PR TITLE
Fix for delete post-config-load.

### PR DESCRIPTION
**Pull request by philliphoff**
Fix for #67 where deleting a configuration file post-load results in an `IOException` on Windows.

Updates `LoadKubeConfig()` to dispose of the opened `Stream` after its contents have been deserialized. Adds a test for fix (that would only ever fail on Windows, though not sure how feasible it would be to add a Windows image to the CI test matrix).

### CODE REVIEW

**Comment by tg123** [comment]
seems many line ending is changed
please unify the line ending

then LGTM

**Comment by philliphoff** [comment]
> seems many line ending is changed
please unify the line ending

It seems that a previous commit had introduced stray LF line endings.  My change (my editor, rather) happened to switch them back to CRLF to be consistent with the rest of the files.

**Comment by brendandburns** [comment]
Lgtm, but needs a CLA signing

**Comment by philliphoff** [comment]
> Lgtm, but needs a CLA signing

Started process for eventual CLA signing; we'll see how long it takes to get through the red tape.

**Comment by tg123** [comment]
seems this commit blocks CLA
a `squash` might fix
```
commit a97329cbdc0bba2b4983e90e6a36e5bfba84cd09
Merge: 64ad901 82db575
Author: Phillip Hoff <pmhoff@Phillips-MacBook-Pro.local>
Date:   Tue Dec 19 08:32:36 2017 -0800

    Merge from master. 
```

**Comment by philliphoff** [comment]
Yes, it’s what I get for merging early in the morning since “I was up anyway”. Will reset or otherwise fix as soon as I get a chance.

**Comment by philliphoff** [comment]
Received approval to sign CLA, and have done so.

**Comment by brendandburns** [comment]
@philliphoff thanks!  Merging.

**Pull request merged**
