### PR TITLE
fix test case fail on windows

### PR DESCRIPTION
**Pull request by tg123**

### CODE REVIEW

**Comment by tg123** [comment]
ping @qmfrederik 

I saw fe029459e0393bbaf7e76ebb81330b17b1accaf8
changed to `OpenCertificateStore` from `new X509Certificate2` due to cert failed on MacOS

but `OpenCertificateStore` does not work on Windows, I added a work around, please have a look.

**Comment by qmfrederik** [comment]
LGTM! Are you trying to set up VSTS/AppVeyor CI builds for Windows? That would be awesome 😄 .

**Comment by tg123** [comment]
@qmfrederik YES

I had set up a VSTS build long time ago. The biggest problem now is that VSTS does not have a public build view.

Not only build and test, I also added resharper code quality check.
Looking forward to integrate it with github.

image

**Comment by qmfrederik** [comment]
@tg123 I think public builds are preview in VSTS now: https://blogs.msdn.microsoft.com/devops/2018/04/27/vsts-public-projects-limited-preview/

**Pull request merged**
