### PR TITLE
Correct the content type in the Kubernetes client.

### PR DESCRIPTION
**Pull request by brendandburns**
This is a temporary fix, we need a fix in upstream swagger, AutoRest or post-processing.

### CODE REVIEW

**Comment by krabhishek8260** [comment]
With this change too the library is still not usable for POST calls without fixing https://github.com/kubernetes-client/csharp/issues/9

**Comment by brendandburns** [comment]
I did a kubernetes PR, so the code is there now:

https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json

We need to re-run AutoRest to regenerate.

**Comment by krabhishek8260** [comment]
Great. I will try to rerun AutoRest and regenerate the client.
Thanks!

**Comment by krabhishek8260** [comment]
The generator Docker image does not have autorest. I added autorest to the Dockerfile but I have not been able to successfully generate the client. I am talking to the autorest team to find out what's wrong.

**Pull request merged**
