### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by AshenW0lf**
Update the copyright notice within the licence agreement, as per the instructions under "APPENDIX: How to apply the Apache License to your work."

### CODE REVIEW

**Comment by AshenW0lf** [comment]
Contributor License Agreement (CLA), has now been signed

**Comment by brendandburns** [comment]
Hrm, I would rather not have to update this every year and the authors are not just me.

Perhaps:

`{year} the Kubernetes Project`

**Comment by AshenW0lf** [comment]
You don't need to update the year, is meant to be the year of first publication so could be a date in the past and the project name would work just as well as the "owners" of the copyright.

**Pull request merged**
