### PR TITLE
fix package version mismatch

### LINKED ISSUE #1575: Nuget package is versioned differently to GitHub
**Describe the bug**
The latest version in this repo is `14.0.8`, however in NuGet, it's tagged as `14.0.9`.

**Kubernetes C# SDK Client Version**
e.g. `14.0.8`

NuGet: https://www.nuget.org/packages/KubernetesClient#versions-body-tab
image

GitHub: https://github.com/kubernetes-client/csharp/releases/tag/v14.0.8

### PR DESCRIPTION
**Pull request by tg123**
fix #1575

regression introduced by #1565

### CODE REVIEW

**Comment by WeihanLi** [comment]
any idea why this caused the breaking?

**Comment by tg123** [comment]
i did git bisect, 
create a tag for each local build test, found that the pr breaks it

i have no idea why

**Comment by WeihanLi** [comment]
wired that from my test, the same version produced for both release and nuget package from the same commit

- https://github.com/WeihanLi/kubernetes-client-csharp/actions/runs/10757117841/job/29830774075
- https://github.com/WeihanLi/kubernetes-client-csharp/actions/runs/10757209841/job/29830988800

**Comment by WeihanLi** [comment]
@tg123 would you mind trying to trigger a release to verify whether we still have this issue, maybe we could wait until the v1.31 is ready

**Comment by tg123** [comment]
sure i did the test locally, seems you are right, it is due to tag not created

**Pull request closed without merging**
