### PR TITLE
Make use of Cert Flags if Set

### PR DESCRIPTION
**Pull request by bootleg224**
The code does not handle the case when Cert Flags are set and Windows is the platform and .net 5 or greater is used

### CODE REVIEW

**Comment by tg123** [comment]
please sign cla

should it be added to 
https://github.com/kubernetes-client/csharp/blob/624ee292f749f8192916b544a0f8d918277ced55/src/KubernetesClient/CertUtils.cs#L99
as well?

**Comment by bootleg224** [comment]
CLA Signed, and  and yes line you identified should also apply cert flags

**Comment by tg123** [comment]
you have make the author of the commit the same email as cla

**Comment by bootleg224** [comment]
I've updated my email in my profile to match the CLA : https://github.com/bootleg224

**Comment by tg123** [comment]
image
github cant figure out the author of this commit

git commit --amend --reset-author

**Comment by tg123** [comment]
ping @bootleg224

**Review by tg123 — APPROVED** [review]
/LGTM

**Comment by m3nax** [comment]
ping @bootleg224

**Comment by bootleg224** [comment]
I have signed the CLA it is unclear what else I need to do

**Comment by tg123** [comment]
@bootleg224 could you please `git commit --reset-author` to set the commit author with sla signed email

**Pull request merged**
