### PR TITLE
align files to .editorconfig

### PR DESCRIPTION
**Pull request by tg123**
eclint fix **/*.cs

check will integrate with CI process
 

#37

@gitfool

### CODE REVIEW

**Comment by gitfool** [comment]
@tg123 I didn't know about [eclint](https://github.com/jedmao/eclint). Nice!

I see all the line endings are still `CRLF` though, despite the `.editorconfig` specifying `LF`. When editing an existing file it seems the existing EOL is preserved. However, when creating a new file (in VS 2017 at least) it will use `LF`, so either `.editorconfig` should be changed to specify `CRLF` or the EOL should be changed to `LF` for all existing files.

**Comment by tg123** [comment]
@gitfool 
only eclint with *.cs
and generated codes are ignored

**Comment by gitfool** [comment]
I ran the same command as you on your branch, `eclint fix **/*.cs`, and all cs files were further updated, as expected, to use `LF` for EOL. So you must've passed `CRLF` on the command-line to eclint; but this has the problem I mention above.

**Comment by tg123** [comment]
@gitfool I checked all .cs are LF except `/src/KubernetesClient/generated/`
for generated they should be handled by autorest.

my command
```
find . -name *.cs -exec file {} \; | grep CRLF | grep -v generated
```

**Comment by gitfool** [comment]
Right. If I clone your repo in WSL then I get `LF`. If I clone in Windows then I get `CRLF`. The problem is that because there's no `.gitattributes` file, it depends on everyone's git client settings. If I edit an existing file on Windows it will be committed using `CRLF`.

The other approach is to remove the `end_of_line` entry from `.editorconfig` and add a `.gitattributes` file. See [dealing-with-line-endings](https://help.github.com/articles/dealing-with-line-endings/#platform-all) and the [gitattributes](https://github.com/alexkaratarakis/gitattributes) repo for some relevant templates. If specified correctly then text files will match the os platform when editing but always be stored in git using `LF`.

**Comment by tg123** [comment]
@gitfool you may be a victim of `autocrlf`

**Comment by gitfool** [comment]
Haha. I've been the victim of many EOL abuses. The point is _everyone_ has their own settings and you can't expect them to comply with your settings, so the best way to address this is with a `.gitattributes` file in the repo. This and `.gitignore` should be the first files added to a new repo. When added late you have to  [renormalize](https://stackoverflow.com/questions/7156694/git-how-to-renormalize-line-endings-in-all-files-in-all-revisions/47580886#47580886) line endings which can make a mess of the repo history.

**Comment by gitfool** [comment]
That's all very well, and is one way to lock things down, but again you've missed the point. You're only considering what you use. A `.gitattributes` file is particularly important for cross-platform projects where developers will use different tools on different operating systems. I give up.

**Comment by tg123** [comment]
@gitfool thanks I see, that is a good idea.
You can create a PR for that

**Comment by gitfool** [comment]
Cool. Will do after this is PR merged, since they'll overlap.

**Comment by brendandburns** [comment]
LGTM.

**Pull request merged**
