### PR TITLE
Gen v1.18.0

### PR DESCRIPTION
**Pull request by tg123**

### CODE REVIEW

**Comment by brendandburns** [comment]
We should really figure out how we want to version things. In the Java client we introduce a new major version for each version of the Kubernetes API. That way people are fore-warned there might be breaking changes.

**Comment by tg123** [comment]
agreed
i think we should include k8s version in nuget version.

**Comment by brendandburns** [comment]
@tg123 can you take care of refining the version, then we can merge this.

**Comment by tg123** [comment]
@brendandburns for sure, I will send out a proposal about how versioning.

**Comment by tg123** [comment]
@brendandburns what do you think if we bump this to `v2.0`
and bump major version on every code generating

this is the solution 1 in #400  (same as java)

**Comment by brendandburns** [comment]
That sounds great to me.

--brendan

________________________________

**Comment by tg123** [comment]
bumped to 2.0 and ready to merge

**Pull request merged**
