### PR TITLE
run generate script for k8s 1.12

### PR DESCRIPTION
**Pull request by tg123**

### CODE REVIEW

**Comment by brendandburns** [comment]
Let's rev the major version of this library to reflect the new version of k8s?

Otherwise, LGTM.

**Comment by tg123** [comment]
1.2.12 or something?

**Comment by itowlson** [comment]
@tg123 It looks previous versions of the library haven't been coupled to the k8s version, which makes sense for when the library needs to be revved independently.  Does this result in any breaking changes?  If not, maybe 1.3.0?

**Comment by brendandburns** [comment]
Yeah, I agree with @itowlson `1.3.0` or `2.0.0`

For the java library we adopted a "new major version for each k8s release" approach, we haven't done that in csharp so far, but maybe we should start (in which case `2.0.0` would be the right version)

**Comment by tg123** [comment]
bumped to 1.3

**Pull request merged**
