### PR TITLE
Handle WebSocket exceptions

### PR DESCRIPTION
**Pull request by qmfrederik**
This is a quick way of handling errors when invoking WebSocket calls. The server returns `400 Bad Request` and a body with details about what went wrong.
Unfortunately, the .NET Core API doesn't give us a way to access the body - see dotnet/corefx#29163.

The workaround, then, is to retry the request as a normal HTTP request and catch the exception as such.

The code will throw a `HttpOperationException` as that is what other methods throw as well.

### CODE REVIEW

**Comment by tintoy** [comment]
Nice workaround, but just want to check - do all k8s Websocket requests support GET? If not, will the error message be the same (rather than indicating an unsupported verb, which might be confusing for callers).

**Comment by qmfrederik** [comment]
Yes, because the [opening handshake of a WebSocket request](https://tools.ietf.org/html/rfc6455#page-6) is a `HTTP GET`.

We've tested it with e.g. `exec` to be sure 😄 .

**Comment by tintoy** [comment]
I'll keep this in mind then when moving us over to the managed `HttpSocketHandler`, then :)

**Comment by brendandburns** [comment]
(also the Java client uses GET exclusively, since that's all Java websockets supports...)

LGTM.

**Pull request merged**
