### PR TITLE
Add http2 keep alive in watch

### PR DESCRIPTION
**Pull request by zhiweiv**
Add http2 keep alive in watch, you can find details in https://github.com/kubernetes-client/csharp/issues/773.

### CODE REVIEW

**Comment by zhiweiv** [comment]
@tg123 
Do you know when will this get merged, we are eager to this it.

**Comment by tg123** [comment]
> @tg123 Do you know when will this get merged, we are eager to test it.

could you please rebase to make test pass?

**Comment by zhiweiv** [comment]
I merged changes from master and rebased, not sure I have done right.

**Comment by zhiweiv** [comment]
Close for wrong rebase.

**Pull request closed without merging**
