### PR TITLE
Update exception message in KubernetesClientConfiguration.InCluster.cs

### PR DESCRIPTION
**Pull request by kentahikaru**
Hello,
i propose updating this exception message as it is misleading. I spent several hours investigating why my container cannot see env variables when in fact it couldn't see service access token.

### CODE REVIEW

**Comment by brendandburns** [comment]
Thank you for the PR, looks like the CLA bot is still not happy, once that is fixed we can merge this.

**Comment by tg123** [comment]
seem your commit's author is different

**Comment by tg123** [comment]
> /easycla

remove the old user and push -f

**Comment by kentahikaru** [comment]
> > /easycla
> 
> remove the old user and push -f

sorry , can you be more specific ? what old user ? where ? on github or in my local git setings ?

**Comment by tg123** [comment]
remove this commit or user
image

**Comment by kentahikaru** [comment]
> remove this commit or user image

Thank you

**Review by tg123 — APPROVED** [review]

**Pull request merged**
