### PR TITLE
Follow up on unused using cleanup

### PR DESCRIPTION
**Pull request by stan-sz**
Visual Studio IDE is able to clean up all occurences.

### CODE REVIEW

**Comment by brendandburns** [comment]
Thanks for the PR, but CI/CD is failing. Please fix.

**Comment by tg123** [comment]
/LGTM

see if rebase could fix

**Comment by stan-sz** [comment]
It turns out VS IDE has problems with static code analysis. I'll close this PR and see if I can get VS to work with this repo.

**Comment by stan-sz** [comment]
See #810

**Pull request closed without merging**
