### PR TITLE
Updated CertificateValidationCallBack to build the CaCert bundle with respect to the rootChain certs to verify that they are correct.

### PR DESCRIPTION
**Pull request by KLazarov**
Implemented fix proposed at: https://github.com/kubernetes-client/csharp/issues/859

### Problem:

Currently the cert verification works only if there is no multi level CA chain that it needs to verify on. If the chain is too long, it will mark `isTrusted` as `false`.

### Suggestion

Instead of trying to directly compare the certs, we actually  build the cert with the help of the chain and verify that it's correct. If the cert or the chain are broken, then `isTrusted` will be `false`. If the chain and cert is correct, then `isTrusted` will be `true`.

### CODE REVIEW

**Comment by tg123** [comment]
could please sign cla and add testcases?

**Comment by KLazarov** [comment]
I have now added the tests for the issue that my code fixes. They are at the bottom of CertificateValidationTests.cs.

I'm still waiting from my company to completly fill out the EasyCLA as we got a bit stuck on it during the weekend.

**Comment by KLazarov** [comment]
The EasyCLA has now been accepted.

**Comment by tg123** [comment]
I looked into the code and seems your #859 code
```
chain.ChainPolicy.CustomTrustStore.Add(ca)
```
makes more sense

here the code is verifying if each ca cert on the cert's chain
should that be verifying cert's chain on a trusted ca?


what is your idea?

**Comment by KLazarov** [comment]
The issue that I stumbled upon and I'm trying to fix here is if there is a chain that is multiple steps long in a single file provided by the Service Account.

As we are running a managed Kubernetes cluster, we get our Certificates generated by the provider, and in our case there are multiple certificates in the same file, and they describe the full chain. By running `chain.Build(cert)` it verifies that the cert that it tries to connect with is actually correctly generated from the Chain.

From what I see
```chain.ChainPolicy.CustomTrustStore.Add(ca)```
will not work, as it still needs to verify that the certificate, and it's easiest to do that using `chain.Build(cert)`.

**Comment by tg123** [comment]
ok could you please also remove `var rootCert = chain.ChainElements[chain.ChainElements.Count - 1].Certificate;` since it is no longer used.

then /LTGM

**Comment by KLazarov** [comment]
Done.

/LTGM

**Comment by KLazarov** [comment]
Btw just read in the guide lines about squashing and commit message length: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#squashing

I will squash it into one commit tomorrow.

**Review by tg123 — COMMENTED** [review]
/LTGM

**Comment by tg123** [comment]
/

> Btw just read in the guide lines about squashing and commit message length: https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#squashing
> 
> I will squash it into one commit tomorrow.

you do not have to, it is automatic

**Review by tg123 — APPROVED** [review]

**Pull request merged**
