### PR TITLE
Fixed regex to quote strings with leading zeros

### PR DESCRIPTION
**Pull request by JHogue-80**
Proposed fix for this issue: https://github.com/kubernetes-client/csharp/issues/663

### CODE REVIEW

**Comment by JHogue-80** [comment]
I signed

**Comment by brendandburns** [comment]
I have no idea why this is failing CI/CD. @tg123 do you know? The error is:

```
Run actions/setup-dotnet@v1
Error: Cannot read property 'filter' of undefined
```

**Comment by tg123** [comment]
original changed to [0-9]
https://github.com/cloudbase/powershell-yaml/blob/master/powershell-yaml.psm1#L276

**Comment by tg123** [comment]
> I have no idea why this is failing CI/CD. @tg123 do you know? The error is:
> 
> 
> 
> ```
> 
> Run actions/setup-dotnet@v1
> 
> Error: Cannot read property 'filter' of undefined
> 
> ```
> 
> 

restart fixed .  seems gh actions' fault

**Pull request merged**
