### PR TITLE
Update Program.cs

### PR DESCRIPTION
**Pull request by dansemedo**
update in doc

### CODE REVIEW

**Comment by dansemedo** [comment]
Hi, I created my account in the Linux Foundation. My id is the same as in GitHub.

**Comment by brendandburns** [comment]
@dansemedo hrm, the CLA bot is still not happy, I'm not sure why...

**Comment by dansemedo** [comment]
@brendandburns, I created the account but I was not aware to sign the CNCF Individual Contributor License. Now I signed and made the login in my account and seems to be OK, It should works now.

**Pull request merged**
