### PR TITLE
Gen v1.22.0

### PR DESCRIPTION
**Pull request by tg123**
include changes from #669
and generated using new generator 

changes comparing to #669 

pretty to `bool?`: seems this is a useless param, should be removed.

### CODE REVIEW

**Comment by brendandburns** [comment]
I merged the generator, can you rebase?

Thanks!

**Comment by brendandburns** [comment]
Can you squash this into 2 commits:

* All the regenerated code
* Any other hand-written changes

That will make this easier to review.

Thanks!

**Comment by tg123** [comment]
> Can you squash this into 2 commits:
> 
> * All the regenerated code
> * Any other hand-written changes
> 
> That will make this easier to review.
> 
> Thanks!

1 generator changes: string to bool?
2 generated code
3 trim ver converted after code generated
4 bump ver

**Comment by brendandburns** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
