### PR TITLE
Move Fractions library inside project

### PR DESCRIPTION
**Pull request by RohanNagar**
Addresses #160.

All of the `Fractions` code is taken as-is on their [master branch](https://github.com/danm-de/Fractions), with the only difference being instead of using generated error messages (i.e. [their `Resources` class](https://github.com/danm-de/Fractions/blob/master/src/Fractions/Properties/Resources.Designer.cs)), I just use the string error messages directly. These are located at:

```
Fractions/Formatter/DefaultFractionFormatter.cs : 16
```
[Link to Changed Line](https://github.com/kubernetes-client/csharp/pull/194/files#diff-9cd265efeb043f6105753d8fdeed1632R16)
[Original Code Before Change](https://github.com/danm-de/Fractions/blob/master/src/Fractions/Formatter/DefaultFractionFormatter.cs#L17)

```
Fractions/Fraction.CompareTo.cs : 23
```
[Link to Changed Line](https://github.com/kubernetes-client/csharp/pull/194/files#diff-3b47fab69319a9c27e26d81b5049f391R23)
[Original Code Before Change](https://github.com/danm-de/Fractions/blob/master/src/Fractions/Fraction.CompareTo.cs#L24)

```
Fractions/Fraction.Math.cs : 113
```
[Link to Changed Line](https://github.com/kubernetes-client/csharp/pull/194/files#diff-aedbc6ac4ec7f519867c21c814914530R113)
[Original Code Before Change](https://github.com/danm-de/Fractions/blob/master/src/Fractions/Fraction.Math.cs#L114)

```
Fractions/Fraction.ConvertFrom.cs : 43
```
[Link to Changed Line](https://github.com/kubernetes-client/csharp/pull/194/files#diff-d2a3d00750aceb0612471fde0f43065dR43)
[Original Code Before Change](https://github.com/danm-de/Fractions/blob/master/src/Fractions/Fraction.ConvertFrom.cs#L44)

Those 4 lines (and the removed `import` at the top of each file) are the only difference from the original code.

### CODE REVIEW

**Comment by brendandburns** [comment]
This looks fine, but please add a README.md which includes a pointer to the original location for the source as well as the reason for the vendoring.

Also, please include the LICENSE.txt file from the original repo in that directory.

Thanks!

**Comment by RohanNagar** [comment]
Thanks @brendanburns. Added the `README` and `LICENSE`.

**Comment by brendandburns** [comment]
LGTM.

Thanks.

**Comment by danm-de** [comment]
Hi, 
Fractions 4.0.1 should be strong named.

**Pull request merged**
