### PR TITLE
Introducing KubernetesClientConfiguration.ClientCertificateKeyStoreFl…

### PR DESCRIPTION
**Pull request by maganvill**
…ags to specify how private key is imported

See #235

### CODE REVIEW

**Comment by maganvill** [comment]
I signed it

**Comment by maganvill** [comment]
@brendandburns, is this a reasonable feature?

**Comment by brendandburns** [comment]
@maganvill I wanted to check w/ the Azure functions folks to see if this was expected and the right solution.

It seems fine with me, but I wanted to double check.

Thanks!

**Pull request merged**
