### PR TITLE
Remove duplicate null check

### PR DESCRIPTION
**Pull request by tylerje**
Resolves issue #382

### CODE REVIEW

**Comment by tylerje** [comment]
How do I resolve the cla/linuxfoundation check? I've added my tylerje account and my org tylerjensen.

**Comment by tg123** [comment]
@tylerje you may want to link to commit email with your github account

**Comment by tylerje** [comment]
> @tylerje you may want to link to commit email with your github account

Did that. Committed. Not sure what else to do. @brendanburns ?

**Comment by tg123** [comment]
image

**Comment by tylerje** [comment]
@tg123 yes. Same person. First commit using VS in fork under my tylerjensen org. Other commits after assuring user.email was assigned. Not sure what to do to fix.

**Comment by tylerje** [comment]
> @tg123 yes. Same person. First commit using VS in fork under my tylerjensen org. Other commits after assuring user.email was assigned. Not sure what to do to fix.

It was VS global settings. Had "Tyler Jensen" as username rather than tylerje. Should we kill this PR and do it over again? Or can it be fixed/overridden by @brendandburns ??

**Comment by tg123** [comment]
try to merge those 3 commits into 1 with the correct author and `push -f`

**Comment by tylerje** [comment]
Closing and will recreate to avoid cla/linuxfoundation check failure.

**Pull request closed without merging**
