### PR TITLE
fix ExecStatus 

### PR DESCRIPTION
**Pull request by tg123**
described in https://kubernetes.io/docs/reference/config-api/client-authentication.v1beta1/#client-authentication-k8s-io-v1beta1-ExecCredential

### CODE REVIEW

**Comment by tg123** [comment]
> /approve

confirmed?

**Comment by dasingh92** [comment]
confirmed by monitoring the workflow for approximately 25 minutes. Usually the error would have occurred by then.

**Comment by dasingh92** [comment]
how soon would the Nuget package be updated with this patch
?

**Comment by tg123** [comment]
Thanks for confirming, I will publish nuget as soon as this PR get merged

**Comment by tg123** [comment]
ping @brendanburns to double confirm

**Comment by tg123** [comment]
ping @brendandburns to double confirm

**Pull request merged**
