### PR TITLE
chore: Annotate NuGet package with link to GitHub repo

### PR DESCRIPTION
**Pull request by tomkerkhove**
Annotate NuGet package with a link to GitHub repo so that automated tools can fetch information such as changelogs.

https://docs.renovatebot.com/nuget/#how-it-works

### CODE REVIEW

**Comment by qmfrederik** [comment]
@tomkerkhove Can you let me know why this is needed?

This project already uses [SourceLink](https://github.com/dotnet/sourcelink) (see #267), with `PublishRepositoryUrl` set, which automatically populates the `RepositoryUrl`.

The [NuGet page for this package](https://www.nuget.org/packages/KubernetesClient/) also points to this repository.

**Comment by qmfrederik** [comment]
And see #276 ;-)

**Comment by tomkerkhove** [comment]
Sorry for my poor memory, lol!

Unfortunately, that doesn't cut it for using Renovate but that's ok 😄

**Comment by qmfrederik** [comment]
😄 

I know next to nothing about Renovate, but I'm curious as to why it doesn't  work this repository.

The specs say:
1. Renovate searches in each repository for any files with a .csproj, .fsproj, or .vbproj extension
2. Existing dependencies are extracted from <PackageReference> and <PackageVersion> tags
3. Renovate looks up the latest version on nuget.org (or on alternate feeds) to determine if any upgrades are available
4. If the source package includes a GitHub URL as its source, and has either a "changelog" file or uses GitHub releases, then Release Notes for each version are embedded in the generated PR

Perhaps the issue is with step 4? Packages are pushed to NuGet from master, and there isn't a formal GitHub release for that version (and no CHANGELOG).

**Comment by tomkerkhove** [comment]
Yes, you are right; thanks for pointing that out - Clearly I should have read that better.

**Pull request closed without merging**
