### PR TITLE
Nodes and pods metrics

### PR DESCRIPTION
**Pull request by alarco-l**
Implementation for usage metrics pulled from metrics server.

Try to address #416

Using as [metrics server API reference](https://github.com/kubernetes/metrics/blob/master/pkg/apis/metrics/v1beta1/types.go)

 - [x] Nodes metrics
 - [x] Pods metrics
 - [x] Pods metrics by namespace
 - [x] Add sample
 - [x] Add tests

### CODE REVIEW

**Comment by brendandburns** [comment]
Super cool! Thanks for the PR!

It is simple enough that I'm ok to merge w/o tests and add them in a second PR, or you can add them to this PR. Your call.

**Comment by alarco-l** [comment]
You can merge it and I will open another one for the tests.

Glad to be able to contribute.

**Comment by alarco-l** [comment]
@brendandburns, I could add the tests on this one.

However, not sure this is the right way to test it.
If you have some insights on that, it could help me.

**Comment by brendandburns** [comment]
Let's merge and then add tests.

Basically you will want to mock out the web server and then test that the client code works correctly to retrieve metrics.

/lgtm
/approve

**Pull request merged**
